version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: account-book-app
    container_name: account-book-app
    environment:
      DB_URL: mysql+pymysql://root:password@db:3306/account_books
    command: uvicorn account_book.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      - db
    working_dir: /code
    volumes:
      - shared-data:/code/account-book-app

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: account-book-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: account_books
    ports:
      - 3306:3306
    volumes:
      - shared-data:/var/lib/mysql

volumes:
  shared-data: